# https://circleci.com/docs/2.0/language-java/
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: guava-cleanser-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: guava-cleanser-{{ checksum "pom.xml" }}
      - run: mvn verify --batch-mode -Dstyle.color=always --errors -Dgpg.skip=true
      - store_test_results:
          path: target/surefire-reports

